"""
URL mappings for the recipe app.
"""
from django.urls import (
    path,     # Importing the path function to define individual URL patterns
    include,  # Importing the include function to include other URL configurations
)

from rest_framework.routers import DefaultRouter  # Importing DefaultRouter to automatically generate URL patterns for the ViewSet

from recipe import views  # Importing the views module from the recipe app


# Create a router object using DefaultRouter
# DefaultRouter automatically generates standard URL patterns for the ViewSet
router = DefaultRouter()

# Register the RecipeViewSet with the router
# This connects the 'recipes' URL prefix with the RecipeViewSet
# It will create endpoints like /recipes/, /recipes/<id>/ for list, retrieve, create, update, delete actions
router.register('recipes', views.RecipeViewSet)

# Set the app name for namespacing
# 'app_name' is used to identify this set of URLs uniquely in the project
app_name = 'recipe'

# Define the URL patterns for this app
# The include function includes the URLs generated by the router
urlpatterns = [
    path('', include(router.urls)),  # Include all URLs provided by the router under the root path
]